### ISSUE TITLE
A Warm Welcome Starting Load Screen

### ISSUE THREAD

**Issue by chompyzilla** [Shockster218/Hobbit-Autosplitter#4]
The autosplitter does not pause upon reaching the AWW starting loading screen, but it does pause as that screen ends. It does not have the same problem with other loading screens, even within the same chapter.

Attached are image 9 from the splits folder, and a video that shows the bugged behaviour along with the normal behaviour on the AWW loading screen when talking to the master.

The OBS feed is cropped to the same section the image is. 

![9](https://user-images.githubusercontent.com/35570156/149648077-33c65bcb-b279-4141-a25a-5a5f50da742d.png)

https://user-images.githubusercontent.com/35570156/149648120-6dae56a4-30f9-4941-8dfd-4660a23bb4fb.mp4

**Comment by Shockster218** [comment]
Thanks for submitting these issue, it's being worked on now. Confirmed bug.

**Comment by Shockster218** [comment]
Fixed in 265c20ad426edccc66376b814a26c3398f69f64a. Scheduled for next release.
